### PR TITLE
V2

### PR DESCRIPTION
**Pull request by Stilic**
This is a WIP, but you can still give your opinion by testing this version! (make sure to follow the guide [here](https://github.com/Stilic/MagEngine-Public/blob/main/README.md#build-instructions) before)

### CODE REVIEW

**Comment by Stilic** [comment]
Also this night I will do a new commit.

**Comment by Stilic** [comment]
@magnumsrtisswag you will need to force-push that for ignore merge conflits btw

**Comment by magnumsrtisswag** [comment]
> @magnumsrtisswag you will need to force-push that for ignore merge conflits btw

This is not going to be merged like i said

**Comment by Stilic** [comment]
> > @magnumsrtisswag you will need to force-push that for ignore merge conflits btw
> 
> This is not going to be merged like i said

bruuuuuuh
ok wait until i finish this and i'll talk of this with you

**Comment by Stilic** [comment]
also if you want i made my own caching system
take it if you need it

**Comment by magnumsrtisswag** [comment]
> > > @magnumsrtisswag you will need to force-push that for ignore merge conflits btw
> > 
> > 
> > This is not going to be merged like i said
> 
> bruuuuuuh ok wait until i finish this and i'll talk of this with you

dude i literally said it was an **unofficial fork**

**Pull request closed without merging**
